suppressPackageStartupMessages(library(oro.nifti))
suppressPackageStartupMessages(library(assertthat))
suppressPackageStartupMessages(library(oro.nifti))
suppressPackageStartupMessages(library(flsa))
suppressPackageStartupMessages(library(genlasso))
suppressPackageStartupMessages(library(plyr))
suppressPackageStartupMessages(library(testthat))
suppressPackageStartupMessages(library(argparse))

source("source_plotter_static.R")
source("source_plotter_interactive.R")
source("source_plotter_outline.R")
source("source_fmri_manipulate.R")
source("source_plotter_preprocess.R")
source("source_main.R")

set.seed(10)
DATE = Sys.Date()
